# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import List

from google.protobuf.descriptor_pb2 import EnumDescriptorProto

from .descriptors import class_decl
from .model import MethodSpec


def render_enum_header(enums: List[EnumDescriptorProto]) -> str:
    lines: List[str] = []
    lines.append("// Generated by protoc-gen-arduinoif. DO NOT EDIT.")
    lines.append("")
    lines.append("#pragma once")
    lines.append("")
    lines.append("#include <stdint.h>")
    lines.append("")

    for enum_desc in enums:
        lines.append(f"typedef enum {enum_desc.name} {{")
        for value in enum_desc.value:
            lines.append(f"  {value.name} = {value.number},")
        lines.append(f"}} {enum_desc.name};")
        lines.append("")

    while lines and lines[-1] == "":
        lines.pop()
    lines.append("")
    return "\n".join(lines)


def _append_enum_decls(body_lines: List[str], enums: List[EnumDescriptorProto]) -> None:
    if not enums:
        return
    for enum_desc in enums:
        body_lines.append(f"typedef enum {enum_desc.name} {{")
        for value in enum_desc.value:
            body_lines.append(f"  {value.name} = {value.number},")
        body_lines.append(f"}} {enum_desc.name};")
        body_lines.append("")


def _render_header(
    includes: List[str],
    namespace_name: str,
    body_lines: List[str],
) -> str:
    lines: List[str] = []
    lines.append("// Generated by protoc-gen-arduinoif. DO NOT EDIT.")
    lines.append("")
    lines.append("#pragma once")
    lines.append("")
    lines.append("#include <cstddef>")
    lines.append("#include <cstdint>")
    for include in includes:
        lines.append(f"#include <{include}>")
    lines.append("")
    if namespace_name:
        lines.append(f"namespace {namespace_name} {{")
        lines.append("")
    lines.extend(body_lines)
    if namespace_name:
        lines.append("")
        lines.append(f"}} // namespace {namespace_name}")
    lines.append("")

    while lines and lines[-1] == "":
        lines.pop()
    lines.append("")
    return "\n".join(lines)


def _append_grouped_methods(
    body_lines: List[str],
    methods: List[MethodSpec],
    emit_method,
) -> None:
    ordered_visibility = ("public", "protected", "private")
    first_section = True
    for visibility in ordered_visibility:
        scoped = [spec for spec in methods if spec.visibility == visibility]
        if not scoped:
            continue
        if not first_section:
            body_lines.append("")
            body_lines.append(f"{visibility}:")
        for spec in scoped:
            emit_method(spec)
        first_section = False


def _append_forwarding_method(
    body_lines: List[str],
    spec: MethodSpec,
    target_expr: str,
    *,
    mark_override: bool = False,
) -> None:
    signature = f"  {spec.decl}"
    if spec.suffix:
        signature += f" {spec.suffix}"
    if mark_override:
        signature += " override"
    body_lines.append(f"{signature} {{")

    call_args = ", ".join(spec.arg_names)
    call_expr = f"{target_expr}.{spec.call_name}({call_args})"
    if spec.returns_void:
        body_lines.append(f"    {call_expr};")
    else:
        body_lines.append(f"    return {call_expr};")
    body_lines.append("  }")
    body_lines.append("")


def render_ifc_header_content(
    include_list: List[str],
    namespace_name: str,
    proto_enums: List[EnumDescriptorProto],
    ifc_class_name: str,
    ifc_methods: List[MethodSpec],
) -> str:
    body_lines: List[str] = []
    _append_enum_decls(body_lines, proto_enums)
    body_lines.append(f"class {ifc_class_name} {{")
    body_lines.append("public:")
    body_lines.append(f"  virtual ~{ifc_class_name}() = default;")
    body_lines.append("")
    _append_grouped_methods(
        body_lines,
        ifc_methods,
        lambda spec: body_lines.append(f"  virtual {spec.decl} = 0;"),
    )
    body_lines.append("};")
    return _render_header(include_list, namespace_name, body_lines)


def render_api_header_content(
    api_includes: List[str],
    namespace_name: str,
    api_class_name: str,
    ifc_class_name: str,
    api_methods: List[MethodSpec],
) -> str:
    body_lines: List[str] = []
    body_lines.append(f"class {api_class_name} : public {ifc_class_name} {{")
    body_lines.append("public:")
    body_lines.append(
        f"  explicit {api_class_name}({ifc_class_name}& impl) : impl_(impl) {{}}"
    )
    body_lines.append("")

    _append_grouped_methods(
        body_lines,
        api_methods,
        lambda spec: _append_forwarding_method(body_lines, spec, "impl_"),
    )
    body_lines.append("private:")
    body_lines.append(f"  {ifc_class_name}& impl_;")
    body_lines.append("};")
    return _render_header(api_includes, namespace_name, body_lines)


def render_service_header_content(
    service_includes: List[str],
    namespace_name: str,
    service_class_name: str,
    service_base_ifc_class_names: List[str],
    service_methods: List[MethodSpec],
) -> str:
    body_lines: List[str] = []
    body_lines.append(class_decl(service_class_name, service_base_ifc_class_names))
    body_lines.append("public:")
    body_lines.append(f"  virtual ~{service_class_name}() = default;")
    body_lines.append("")
    _append_grouped_methods(
        body_lines,
        service_methods,
        lambda spec: body_lines.append(f"  virtual {spec.decl} = 0;"),
    )
    body_lines.append("};")
    return _render_header(service_includes, namespace_name, body_lines)


def render_service_impl_header_content(
    service_impl_includes: List[str],
    namespace_name: str,
    service_impl_class_name: str,
    service_class_name: str,
    api_class_name: str,
    api_member_name: str,
    service_impl_methods: List[MethodSpec],
    generate_api_class: bool,
) -> str:
    body_lines: List[str] = []
    if not generate_api_class:
        body_lines.append(f"class {api_class_name};")
        body_lines.append("")

    body_lines.append(
        f"class {service_impl_class_name} : public {service_class_name} {{"
    )
    body_lines.append("public:")
    body_lines.append(
        f"  explicit {service_impl_class_name}({api_class_name}& api) : {api_member_name}(api) {{}}"
    )
    body_lines.append("")
    _append_grouped_methods(
        body_lines,
        service_impl_methods,
        lambda spec: _append_forwarding_method(
            body_lines, spec, api_member_name, mark_override=True
        ),
    )
    body_lines.append("private:")
    body_lines.append(f"  {api_class_name}& {api_member_name};")
    body_lines.append("};")
    return _render_header(service_impl_includes, namespace_name, body_lines)
