# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

import sys
import types
from pathlib import Path, PurePosixPath
from typing import Iterator, Tuple

from google.protobuf.compiler import plugin_pb2
from google.protobuf.descriptor_pb2 import EnumDescriptorProto

from .service_renderer import ServiceRenderer
from .service_model_builder import ServiceModelBuilder
from .request_context import RequestContext

__all__ = [
    "main",
]


def _load_arduino_opts_pb2() -> types.ModuleType:
    import importlib.util
    import os
    import re
    import subprocess
    import tempfile

    def patch_runtime_guard(pb2_path: Path) -> None:
        text = pb2_path.read_text(encoding="utf-8")
        import_line = "from google.protobuf import runtime_version as _runtime_version\n"
        import_guard = (
            "try:\n"
            "  from google.protobuf import runtime_version as _runtime_version\n"
            "except ImportError:\n"
            "  _runtime_version = None\n"
        )
        if import_line in text and import_guard not in text:
            text = text.replace(import_line, import_guard)

        pattern = re.compile(
            r"_runtime_version\.ValidateProtobufRuntimeVersion\(\n"
            r"(?P<body>(?:\s+.*\n)+?)"
            r"\)\n"
        )
        match = pattern.search(text)
        if match and "if _runtime_version is not None:" not in text:
            body = "".join(f"  {line}" for line in match.group("body").splitlines(True))
            wrapped = (
                "if _runtime_version is not None:\n"
                "  _runtime_version.ValidateProtobufRuntimeVersion(\n"
                f"{body}"
                "  )\n"
            )
            text = text[: match.start()] + wrapped + text[match.end() :]

        pb2_path.write_text(text, encoding="utf-8")

    def generate_pb2_to_temp() -> Path:
        proto_dir = Path(__file__).resolve().parents[2] / "idl" / "proto"
        proto_file = proto_dir / "arduino_opts.proto"
        cache_dir = Path(tempfile.gettempdir()) / "protoc_gen_arduinoif_pb2"
        cache_dir.mkdir(parents=True, exist_ok=True)
        pb2_path = cache_dir / "arduino_opts_pb2.py"

        should_generate = True
        if pb2_path.exists():
            should_generate = pb2_path.stat().st_mtime < proto_file.stat().st_mtime

        if should_generate:
            subprocess.run(
                [
                    "protoc",
                    f"--proto_path={proto_dir}",
                    f"--python_out={cache_dir}",
                    str(proto_file),
                ],
                check=True,
            )
            patch_runtime_guard(pb2_path)

        return pb2_path

    pb2_path = os.environ.get("PROTOC_GEN_ARDUINOIF_PB2")
    if pb2_path and Path(pb2_path).exists():
        source_path = Path(pb2_path)
        module_name = "_protoc_gen_arduinoif_arduino_opts_pb2"
    else:
        source_path = generate_pb2_to_temp()
        module_name = "_protoc_gen_arduinoif_arduino_opts_pb2_generated"

    spec = importlib.util.spec_from_file_location(module_name, source_path)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"failed to load arduino_opts_pb2 from '{source_path}'")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def _iter_generated_files(
    request: plugin_pb2.CodeGeneratorRequest,
    arduino_opts_pb2: types.ModuleType,
) -> Iterator[Tuple[str, str]]:
    ServiceModelBuilder.configure_options_module(arduino_opts_pb2)
    context = RequestContext.build(request)

    for proto_file in request.proto_file:
        if not context.is_requested_proto(proto_file.name):
            continue

        if proto_file.enum_type and not proto_file.service:
            yield (
                f"{PurePosixPath(proto_file.name).stem}_types.h",
                _render_enum_header(list(proto_file.enum_type)),
            )

        for service in proto_file.service:
            service_model = ServiceModelBuilder.build(
                service,
                proto_file.package,
                list(proto_file.enum_type),
                context,
            )
            yield from ServiceRenderer(service_model).iter_headers()


def _render_enum_header(enums: list[EnumDescriptorProto]) -> str:
    lines = [
        "// Generated by protoc-gen-arduinoif. DO NOT EDIT.",
        "",
        "#pragma once",
        "",
        "#include <stdint.h>",
        "",
    ]

    for enum_desc in enums:
        lines.extend([f"typedef enum {enum_desc.name} {{"])
        lines.extend(f"  {value.name} = {value.number}," for value in enum_desc.value)
        lines.extend([f"}} {enum_desc.name};", ""])

    while lines[-1] == "":
        lines.pop()
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    arduino_opts_pb2 = _load_arduino_opts_pb2()
    request = plugin_pb2.CodeGeneratorRequest()
    request.ParseFromString(sys.stdin.buffer.read())
    response = plugin_pb2.CodeGeneratorResponse()

    try:
        for name, content in _iter_generated_files(request, arduino_opts_pb2):
            output = response.file.add()
            output.name = name
            output.content = content
    except Exception as error:
        response.error = str(error)

    if hasattr(plugin_pb2.CodeGeneratorResponse, "FEATURE_PROTO3_OPTIONAL"):
        response.supported_features = (
            plugin_pb2.CodeGeneratorResponse.FEATURE_PROTO3_OPTIONAL
        )

    sys.stdout.buffer.write(response.SerializeToString())
    return 0
