# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from pathlib import PurePosixPath
from typing import Iterator, List, Tuple

from google.protobuf.descriptor_pb2 import EnumDescriptorProto

__all__ = [
    "EnumRenderer",
]


class EnumRenderer:
    def __init__(self, proto_name: str, enums: List[EnumDescriptorProto]) -> None:
        self._proto_name = proto_name
        self._enums = enums

    def __iter__(self) -> Iterator[Tuple[str, str]]:
        yield self._header_name(), self._render_header_content()

    def _header_name(self) -> str:
        return f"{PurePosixPath(self._proto_name).stem}_types.h"

    def _render_header_content(self) -> str:
        lines = [
            "// Generated by protoc-gen-arduinoif. DO NOT EDIT.",
            "",
            "#pragma once",
            "",
            "#include <stdint.h>",
            "",
        ]

        for enum_desc in self._enums:
            lines.extend([f"typedef enum {enum_desc.name} {{"])
            lines.extend(
                f"  {value.name} = {value.number}," for value in enum_desc.value
            )
            lines.extend([f"}} {enum_desc.name};", ""])

        while lines[-1] == "":
            lines.pop()
        lines.append("")
        return "\n".join(lines)
