# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Callable, List

from google.protobuf.descriptor_pb2 import EnumDescriptorProto

from .model import MethodSpec, PlannedMethod, ServicePlan

__all__ = [
    "render_enum_header",
    "render_ifc_header_content",
    "render_api_header_content",
    "render_service_header_content",
    "render_service_impl_header_content",
]


def _class_decl(class_name: str, base_classes: List[str]) -> str:
    if not base_classes:
        return f"class {class_name} {{"
    bases = ", ".join(f"public {base_class}" for base_class in base_classes)
    return f"class {class_name} : {bases} {{"


class _ServicePlanRenderer:
    def __init__(self, plan: ServicePlan) -> None:
        self._plan = plan

    def render_ifc_header_content(self) -> str:
        body_lines: List[str] = []
        self._append_enum_decls(body_lines)
        body_lines.append(f"class {self._plan.ifc_name} {{")
        body_lines.append("public:")
        body_lines.append(f"  virtual ~{self._plan.ifc_name}() = default;")
        body_lines.append("")
        self._append_surface_methods(
            body_lines,
            lambda planned: planned.in_ifc,
            lambda spec: body_lines.append(f"  virtual {spec.decl} = 0;"),
        )
        body_lines.append("};")
        return self._render_header(self._plan.include_list, body_lines)

    def render_api_header_content(self) -> str:
        body_lines: List[str] = []
        body_lines.append(
            f"class {self._plan.api_name} : public {self._plan.ifc_name} {{"
        )
        body_lines.append("public:")
        body_lines.append(
            f"  explicit {self._plan.api_name}({self._plan.ifc_name}& impl) : impl_(impl) {{}}"
        )
        body_lines.append("")
        self._append_surface_methods(
            body_lines,
            lambda planned: planned.in_api,
            lambda spec: self._append_forwarding_method(body_lines, spec, "impl_"),
        )
        body_lines.append("private:")
        body_lines.append(f"  {self._plan.ifc_name}& impl_;")
        body_lines.append("};")
        return self._render_header(self._plan.api_includes, body_lines)

    def render_service_header_content(self) -> str:
        body_lines: List[str] = []
        body_lines.append(
            _class_decl(
                self._plan.service_name,
                self._plan.service_base_ifc_class_names,
            )
        )
        body_lines.append("public:")
        body_lines.append(f"  virtual ~{self._plan.service_name}() = default;")
        body_lines.append("")
        self._append_surface_methods(
            body_lines,
            lambda planned: planned.in_service,
            lambda spec: body_lines.append(f"  virtual {spec.decl} = 0;"),
        )
        body_lines.append("};")
        return self._render_header(self._plan.service_includes, body_lines)

    def render_service_impl_header_content(self) -> str:
        body_lines: List[str] = []
        if not self._plan.generate_api:
            body_lines.append(f"class {self._plan.api_name};")
            body_lines.append("")

        body_lines.append(
            f"class {self._plan.service_impl_name} : public {self._plan.service_name} {{"
        )
        body_lines.append("public:")
        body_lines.append(
            f"  explicit {self._plan.service_impl_name}({self._plan.api_name}& api) : {self._plan.api_member_name}(api) {{}}"
        )
        body_lines.append("")
        self._append_surface_methods(
            body_lines,
            lambda planned: planned.in_service_impl,
            lambda spec: self._append_forwarding_method(
                body_lines,
                spec,
                self._plan.api_member_name,
                mark_override=True,
            ),
        )
        body_lines.append("private:")
        body_lines.append(f"  {self._plan.api_name}& {self._plan.api_member_name};")
        body_lines.append("};")
        return self._render_header(self._plan.service_impl_includes, body_lines)

    def _append_enum_decls(self, body_lines: List[str]) -> None:
        if not self._plan.proto_enums:
            return
        for enum_desc in self._plan.proto_enums:
            body_lines.append(f"typedef enum {enum_desc.name} {{")
            for value in enum_desc.value:
                body_lines.append(f"  {value.name} = {value.number},")
            body_lines.append(f"}} {enum_desc.name};")
            body_lines.append("")

    def _render_header(self, includes: List[str], body_lines: List[str]) -> str:
        lines: List[str] = []
        lines.append("// Generated by protoc-gen-arduinoif. DO NOT EDIT.")
        lines.append("")
        lines.append("#pragma once")
        lines.append("")
        lines.append("#include <cstddef>")
        lines.append("#include <cstdint>")
        for include in includes:
            lines.append(f"#include <{include}>")
        lines.append("")
        if self._plan.namespace_name:
            lines.append(f"namespace {self._plan.namespace_name} {{")
            lines.append("")
        lines.extend(body_lines)
        if self._plan.namespace_name:
            lines.append("")
            lines.append(f"}} // namespace {self._plan.namespace_name}")
        lines.append("")

        while lines and lines[-1] == "":
            lines.pop()
        lines.append("")
        return "\n".join(lines)

    def _append_surface_methods(
        self,
        body_lines: List[str],
        in_surface: Callable[[PlannedMethod], bool],
        emit_method: Callable[[MethodSpec], None],
    ) -> None:
        public_methods: List[MethodSpec] = []
        protected_methods: List[MethodSpec] = []
        private_methods: List[MethodSpec] = []

        for planned in self._plan.methods:
            if not in_surface(planned):
                continue
            spec = planned.spec
            if spec.visibility == "protected":
                protected_methods.append(spec)
            elif spec.visibility == "private":
                private_methods.append(spec)
            else:
                public_methods.append(spec)

        for spec in public_methods:
            emit_method(spec)

        if protected_methods:
            body_lines.append("")
            body_lines.append("protected:")
            for spec in protected_methods:
                emit_method(spec)

        if private_methods:
            body_lines.append("")
            body_lines.append("private:")
            for spec in private_methods:
                emit_method(spec)

    @staticmethod
    def _append_forwarding_method(
        body_lines: List[str],
        spec: MethodSpec,
        target_expr: str,
        *,
        mark_override: bool = False,
    ) -> None:
        signature = f"  {spec.decl}"
        if spec.suffix:
            signature += f" {spec.suffix}"
        if mark_override:
            signature += " override"
        body_lines.append(f"{signature} {{")

        call_args = ", ".join(spec.arg_names)
        call_expr = f"{target_expr}.{spec.call_name}({call_args})"
        if spec.returns_void:
            body_lines.append(f"    {call_expr};")
        else:
            body_lines.append(f"    return {call_expr};")
        body_lines.append("  }")
        body_lines.append("")


def render_enum_header(enums: List[EnumDescriptorProto]) -> str:
    lines: List[str] = []
    lines.append("// Generated by protoc-gen-arduinoif. DO NOT EDIT.")
    lines.append("")
    lines.append("#pragma once")
    lines.append("")
    lines.append("#include <stdint.h>")
    lines.append("")

    for enum_desc in enums:
        lines.append(f"typedef enum {enum_desc.name} {{")
        for value in enum_desc.value:
            lines.append(f"  {value.name} = {value.number},")
        lines.append(f"}} {enum_desc.name};")
        lines.append("")

    while lines and lines[-1] == "":
        lines.pop()
    lines.append("")
    return "\n".join(lines)


def render_ifc_header_content(
    plan: ServicePlan,
) -> str:
    return _ServicePlanRenderer(plan).render_ifc_header_content()


def render_api_header_content(
    plan: ServicePlan,
) -> str:
    return _ServicePlanRenderer(plan).render_api_header_content()


def render_service_header_content(
    plan: ServicePlan,
) -> str:
    return _ServicePlanRenderer(plan).render_service_header_content()


def render_service_impl_header_content(
    plan: ServicePlan,
) -> str:
    return _ServicePlanRenderer(plan).render_service_impl_header_content()
